config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "costs#index"
  resources :costs
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :sale
    validates :food_cost
    validates :utility_cost
    validates :labor_cost
    validates :rent
    validates :supply
    validates :inventory
    validates :last_inventory
    validates :date
  end
end

app/models/event.rb
class Event < ApplicationRecord
  with_options presence: true do
    validates :title
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :costs

  validates :name, presence: true
  def self.guest
    find_or_create_by!(email: 'aaa@aaa.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'サンプル'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @costs = Cost.all.order(date: "DESC")
    @events = Event.all
  end

  def new
    @cost = Cost.new
  end

  def create
    @cost = Cost.new(cost_params)
    if @cost.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
    @cost = Cost.find(params[:id])
    @data = [['食材原価', @cost.food_cost], ['光熱費', @cost.utility_cost], ['人件費', @cost.labor_cost], ['家賃', @cost.rent], ['消耗品費', @cost.supply], ['その他', @cost.other]]
    @data_all = [['食材原価', @cost.food_cost], ['光熱費', @cost.utility_cost], ['人件費', @cost.labor_cost], ['家賃', @cost.rent], ['消耗品費', @cost.supply], ['その他', @cost.other], ['当月棚卸金額', @cost.inventory]]
    @genkaritu = sprintf("%.2f",(@cost.last_inventory + @cost.food_cost - @cost.inventory) * 100 / @cost.sale.to_f)
    @arari = (@cost.sale - @cost.food_cost) / 1000
    @eigyourieki = (@cost.sale - (@cost.food_cost + @cost.utility_cost + @cost.labor_cost + @cost.rent + @cost.supply + @cost.other)) / 1000
  end

  def cost_params
    params.require(:cost).permit(:sale, :food_cost, :utility_cost, :labor_cost, :rent, :supply, :other, :inventory, :last_inventory, :date).merge(user_id: current_user.id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index



  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    Event.create(event_parameter)
    redirect_to root_path
  end

  private

  def event_parameter
    params.require(:event).permit(:title, :content, :start_time)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/costs/index.html.erb
<%= render "shared/header" %>

<div class='title-contents'>
    <h2 class='service-title'>
      棚卸しアプリ
    </h2>
    <p class='service-explain'>
      毎月の棚卸しを簡単に行える
    </p>
    <p class='service-explain'>
      月末の締めの予定を立てられる
    </p>
    <p class='service-explain'>
      原価率、利益が簡単に出力される
    </p>
</div>

<div class="main_contents">
<div class="enter_title">
  <p>棚卸し詳細一覧</p>
</div>

<%= link_to '月次金額登録', new_cost_path, class: "cost_btn" %>


<div class="cost_main">
<% @costs.each do |cost| %>
<li class='list'>
  <%= link_to cost_path(cost.id) do %>
  <div class="card">
  <h3 class="content-1"><%= cost.date.year %>年<%= cost.date.month %>月</h3>
  <a class="content-">詳細はこちら</a>
  </div>
  <% end %>
</li>
<% end %>
</div>


<div class="enter_title">
  <p>棚卸しカレンダー</p>
</div>

<div class="calender">
  <div class="calender_head">
    <%= link_to '予定を登録', new_event_path, class: "calender_btn" %>
  </div>
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>

  <% events.each do |event| %>
    <div>
      <%= event.title %>
      <%= event.content %>
    </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/costs/new.html.erb
<%= render "shared/header" %>

<div class="costs_new_main">
  <div class="container">
    <h3>月次金額を登録する</h3>
    <div class="create_costs">
    <%= form_with(model: @cost, local: true) do |form| %>
      <div class='costs_item'>
      <%= raw sprintf(
                  form.date_select(
                    :date,
                    class:'select-year-month',
                    use_month_numbers: true,
                    discard_day: true,
                    prompt:'--',
                    start_year: 2011,
                    end_year: (Time.now.year),
                    date_separator: '%s'),
                  "<p> 年 </p>") + "<p> 月 </p>" %>
      </div>
      <div class="costs_item">
        ■ 売り上げ金額を入力してください　　　<%= form.text_field :sale, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ 食材原価を入力してください　　　　　<%= form.text_field :food_cost, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ 光熱費を入力してください　　　　　　<%= form.text_field :utility_cost, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ 人件費を入力してください　　　　　　<%= form.text_field :labor_cost, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ 家賃を入力してください　　　　　　　<%= form.text_field :rent, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ 消耗品費を入力してください　　　　　<%= form.text_field :supply, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ その他の金額を入力してください　　　<%= form.text_field :other, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ 当月の棚卸し金額を入力してください　<%= form.text_field :inventory, placeholder: "￥" %>
      </div>
      <div class="costs_item">
        ■ 前月の棚卸し金額を入力してください　<%= form.text_field :last_inventory, placeholder: "￥" %>
      </div>

      <%= form.submit "登録",class: "login_btn" %>
    <% end %>
    </div>

    <%= link_to "戻る", root_path, class: "back_btn" %>

  </div>


</div>

app/views/costs/show.html.erb
<%= render "shared/header" %>

<div class="costs_show_main">
  <h1><%= @cost.date.year %>年<%= @cost.date.month %>月</h1>


  <div class="chart">
    <div class="chart-detail">
      <%= pie_chart @data, width: "45vw", height: "40vh", title: "支出の割合" %>
    </div>
    <div class="chart-detail">
      <%= image_tag "main.png" %>
    </div>
  </div>

  <div class="costs-explain">
    <h2><span>Cost rate</span>食材原価率は　<%= @genkaritu %>％　です</h2>
  </div>

  <div class="costs-explain">
    <h2><span>Gross profit</span>粗利は　<%= @arari %>千円　です</h2>
  </div>

  <div class="costs-explain">
    <h2><span>Operating income</span>営業利益は　<%= @eigyourieki %>千円　です</h2>
  </div>



  <table class="show_table">
  <tr class="show_tr">
    <th class="show_th">売り上げ</th>
    <td class="show_td">¥　<%= @cost.sale %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th">食材原価</th>
    <td class="show_td">¥　<%= @cost.food_cost %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th">光熱費</th>
    <td class="show_td">¥　<%= @cost.utility_cost %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th">人件費</th>
    <td class="show_td">¥　<%= @cost.labor_cost %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th">家賃</th>
    <td class="show_td">¥　<%= @cost.rent %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th">消耗品費</th>
    <td class="show_td">¥　<%= @cost.supply %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th">その他金額</th>
    <td class="show_td">¥　<%= @cost.other %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th"><%= @cost.date.month %>月棚卸し金額</th>
    <td class="show_td">¥　<%= @cost.inventory %></td>
  </tr>
  <tr class="show_tr">
    <th class="show_th">前月棚卸し金額</th>
    <td class="show_td">¥　<%= @cost.last_inventory %></td>
  </tr>
</table>

  <%= link_to "戻る", root_path, class: "back_btn_show" %>


</div>

app/views/events/new.html.erb
<%= render "shared/header" %>

<div class="events_new_main">

<h3>カレンダーに予定を登録する</h3>

<%= form_with(model: @event, local: true) do |form| %>
  
  <div class="events_item">
    ■ 予定を入力してください　　　　<%= form.text_field :title %>
  </div>
  <div class="events_item">
    ■ 日付・時間を入力してください　<%= form.datetime_select :start_time %>
  </div>
  <div class="events_item">
    ■ 予定の詳細を入力してください　<%= form.text_field :content %>
  </div>
  <div class="events_item">
    <%= form.submit "登録",class: "login_btn" %>
  </div>

<% end %>

<%= link_to "戻る", root_path, class: "back_btn" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Inventory</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to '月次金額登録', new_cost_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to '予定登録', new_event_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %>年<%= t('date.month_names')[start_date.month] %> </span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>